### ISSUE TITLE
KeyError: 'project'

### ISSUE THREAD

**Issue by meichthys** [perfectra1n/pytrilium#14]
Whenever I try to create a PyTrilium object with my trilium instance url and password/token i get the following error: 
```
.venv/lib/python3.10/site-packages/pytrilium/PyTriliumClient.py", line 156, in get_version
    return self.get_pyproject_toml()["project"]["version"]
KeyError: 'project'
```

**Comment by perfectra1n** [comment]
Hey there @meichthys, sorry about that. I should do better testing to make sure that silly things like that don't pop up. TIL that `pyproject.toml` isn't shipped with `pip` packages. This should be fixed in 233398674bf9855cbe68fdca452bd418875322ec, let me know if it works as expected now!
